// Generated by CoffeeScript 1.8.0
(function() {
  var Adapter, Bot, CatchAllMessage, ChatUser, EnterMessage, LeaveMessage, Listener, Response, TextListener, TextMessage, TopicMessage, _ref, _ref1;

  ChatUser = require('./user');

  Bot = require('./bot');

  Adapter = require('./adapter');

  Response = require('./response');

  _ref = require('./listener'), Listener = _ref.Listener, TextListener = _ref.TextListener;

  _ref1 = require('./message'), TextMessage = _ref1.TextMessage, EnterMessage = _ref1.EnterMessage, LeaveMessage = _ref1.LeaveMessage, TopicMessage = _ref1.TopicMessage, CatchAllMessage = _ref1.CatchAllMessage;

  module.exports = {
    ChatUser: ChatUser,
    Bot: Bot,
    Adapter: Adapter,
    Response: Response,
    Listener: Listener,
    TextListener: TextListener,
    TextMessage: TextMessage,
    EnterMessage: EnterMessage,
    LeaveMessage: LeaveMessage,
    TopicMessage: TopicMessage,
    CatchAllMessage: CatchAllMessage
  };

  module.exports.loadBot = function(adapterPath, adapterName, botName) {
    return new Bot(adapterPath, adapterName, botName);
  };

}).call(this);
