// Generated by CoffeeScript 1.8.0
(function() {
  var Response,
    __slice = [].slice;

  Response = (function() {
    function Response(bot, message, match) {
      this.bot = bot;
      this.message = message;
      this.match = match;
      this.envelope = {
        room: this.message.room,
        user: this.message.user,
        message: this.message
      };
    }

    Response.prototype.send = function() {
      var strings, _ref;
      strings = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return (_ref = this.bot.adapter).send.apply(_ref, [this.envelope].concat(__slice.call(strings)));
    };

    Response.prototype.emote = function() {
      var strings, _ref;
      strings = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return (_ref = this.bot.adapter).emote.apply(_ref, [this.envelope].concat(__slice.call(strings)));
    };

    Response.prototype.reply = function() {
      var strings, _ref;
      strings = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return (_ref = this.bot.adapter).reply.apply(_ref, [this.envelope].concat(__slice.call(strings)));
    };

    Response.prototype.random = function(items) {
      return items[Math.floor(Math.random() * items.length)];
    };

    Response.prototype.finish = function() {
      return this.message.finish();
    };

    Response.prototype.http = function(url) {
      return this.bot.http(url);
    };

    return Response;

  })();

  module.exports = Response;

}).call(this);
