// Generated by CoffeeScript 1.8.0
(function() {
  var ChatUser;

  ChatUser = (function() {
    function ChatUser(id, options) {
      var k;
      this.id = id;
      if (options == null) {
        options = {};
      }
      for (k in options || {}) {
        this[k] = options[k];
      }
      this['name'] || (this['name'] = this.id.toString());
    }

    return ChatUser;

  })();

  module.exports = ChatUser;

}).call(this);
